### ISSUE TITLE
Problem setting up the build container and running the build scripts

### ISSUE THREAD

**Issue by rmam-spinworks** [cgi-eoss/fstep#74]
The "Building" section in the FS-TEP's README.md includes an example showcasing how FS-TEP can be built with a Docker build environment.  However, I'm experiencing some problems getting it to work.

Here's a copy of the build script included in README.md:

```
docker build -t fstep-build ./build/
docker run -v $PWD:$PWD -w $PWD fstep-build ./build/fstep.sh
docker run -v $PWD:$PWD -w $PWD fstep-build ./build/zoo-project.sh
docker run -v $PWD:$PWD -w $PWD -e HOME=$PWD/.home fstep-build ./build/standalone-dist.sh
```

The script fails at the 2nd step.  Here's the output:

```
$ docker run -v $PWD:$PWD -w $PWD fstep-build ./build/fstep.sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./build/fstep.sh\": stat ./build/fstep.sh: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled
```

Here's a list of the files found in ./build :
```
$ docker run -v $PWD:$PWD -w $PWD fstep-build ls ./build/
Dockerfile
sshdBootstrap.sh
```

**Comment by antonio-cuomo** [comment]
Instructions had become obsolete, now updated with the correct commands:

docker build -t fstep-build ./build/
docker run -v $PWD:$PWD -w $PWD fstep-build gradle build buildDist --parallel
